services:
  backend:
    build: ./backend
    container_name: traffic-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance
      - ./sumo:/sumo   
    # env_file:
    # - ./backend/.env
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build: ./frontend
    container_name: traffic-frontend
    ports:
      - "3000:3000"
    # env_file:
    # - ./frontend/.env.docker
